#!/Users/millarm/projects/tellybug/webserver/bin/python

from optparse import OptionParser
import subprocess
import os
import signal
import sys

local_db = None

def signal_handler(signal, frame):
    if local_db:
        local_db.terminate()
    sys.exit(0)

signal.signal(signal.SIGINT, signal_handler)
signal.signal(signal.SIGTERM, signal_handler)

def main():
    usage = "usage: %prog [options] arg"
    parser = OptionParser(usage)
    parser.add_option('--port', dest="port",
                      help=" The port number that DynamoDB Local will use to communicate with your application. If you do not specify this option, the default port is 8000.")

    parser.add_option('--dbPath', dest='dbPath',
                      help="The directory where DynamoDB Local will write its database file. If you do not specify this option, the file will be written to the current directory.")

    parser.add_option('--inMemory', dest='inMemory',
        help='Instead of using a database file, DynamoDB Local will run in memory. When you stop DynamoDB Local, none of the data will be saved.')

    (options, args) = parser.parse_args()

    command = ['java', '-Djava.library.path=./DynamoDBLocal_lib', '-jar', os.path.join(os.path.dirname(os.path.abspath(__file__)),'DynamoDBLocal.jar')]

    if options.port:
        command.extend(['-port',options.port])

    if options.dbPath:
        command.extend(['-dbPath',options.dbPath])
    elif options.inMemory:
        command.append('-inMemory')

    global local_db
    local_db = subprocess.Popen(command)
    signal.pause()

if __name__ == "__main__":
    main()
